# Generated by Django 3.2.7 on 2021-09-17 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('link', models.CharField(max_length=1000)),
                ('new', models.CharField(max_length=6)),
                ('uid', models.UUIDField(default=uuid.UUID('5cd6def4-f172-4fbc-b83d-6025e83bf03c'), primary_key=True, serialize=False)),
            ],
        ),
    ]
